version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: ShopBd
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: Shop
    ports:
      - "5432:5432"
    volumes:
      - shop-data:/var/lib/postgresql/data

  web1:
    build:
      context: .
      dockerfile: Web/Dockerfile
    container_name: ShopWeb1
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
    expose:
      - "8080"

  web2:
    build:
      context: .
      dockerfile: Web/Dockerfile
    container_name: ShopWeb2
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
    expose:
      - "8080"
  
  proxy:
    image: nginx:mainline
    container_name: ShopProxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
          - web1
          - web2

volumes:
  shop-data:
